routes/web.php
<?php


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DebtorController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\BankAccountController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});




Route::get('/offline', function () {
    return view('vendor.laravelpwa.offline');
});

Auth::routes();
Route::prefix("/accounts")->group(function () {
    Route::get('/', [AccountController::class, 'index'])->name('accounts.index');
    Route::get('/add', [AccountController::class, 'create'])->name('accounts.add');
    Route::post('/add', [AccountController::class, 'store'])->name('accounts.add');
    Route::get('/edit/{account}', [AccountController::class, 'edit'])->name('accounts.edit');
    Route::post('/edit/{account}', [AccountController::class, 'update'])->name('accounts.edit');
    Route::get('/accounts/print/account/{account}', [AccountController::class, 'print'])->name('accounts.print');
    Route::get('/accounts/send/account/{account}', [AccountController::class, 'send'])->name('accounts.send');
});

Route::prefix("/debtors")->group(function () {
    Route::get('/', [DebtorController::class, 'index'])->name('debtors.index');
    Route::post('add', [DebtorController::class, 'store'])->name('debtors.add-debtor');
    Route::post('edit', [DebtorController::class, 'update'])->name('debtors.edit-debtor');
});

Route::prefix("/bank_accounts")->group(function () {
    Route::get('/', [BankAccountController::class, 'index'])->name('bank_accounts.index');
    Route::post('add', [BankAccountController::class, 'store'])->name('bank_accounts.add');
    Route::post('edit', [BankAccountController::class, 'update'])->name('bank_accounts.edit');
});


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/logout',  [App\Http\Controllers\Auth\LoginController::class, 'logout']);

app/Models/Account.php
<?php

namespace App\Models;

use NumberFormatter;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Account extends Model
{
    use HasFactory;
    protected $table = 'accounts';
    protected $fillable = [
        'user_id',
        'account_id',
        'bank_account_id',
        'note',
        'amount',
        'link_pay'
    ];

    public function user(){
        return $this->belongsTo('App\Models\User');
	}

    public function debtor(){
        return $this->belongsTo('App\Models\Debtor');
	}

    public function bankAccount(){
        return $this->belongsTo('App\Models\BankAccount');
	}

    public function items(){
        return $this->hasMany('App\Models\AccountItem','account_id');
    }

    public function getTotalAccountAmountInLettersAttribute(){
        $amount = new NumberFormatter("es", NumberFormatter::SPELLOUT);
        $totals = $this->items()->sum('amount');
        $type_currency = $totals > 999999 ? ' de pesos' : ' pesos';
        return ucfirst($amount->format($totals) .$type_currency);
    }

    public function getTotalAccountAmountAttribute(){
        return $this->items()->sum('amount');
    }

    public function getDateFormatLongLetterAttribute(){
        return date('M j, Y', strtotime($this->created_at)) ;
    }
}

app/Http/Controllers/AccountController.php
<?php

namespace App\Http\Controllers;

use App\Models\Debtor;
use App\Models\Account;
use Barryvdh\DomPDF\PDF;
use Illuminate\Http\Request;
use App\Http\Services\ScheduledEmailService;
use App\Models\AccountItem;
use App\Models\BankAccount;

class AccountController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $accounts = Account::where('user_id', auth()->id())->get();
        return view('accounts.index', compact('accounts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $bank_accounts = BankAccount::where('user_id', auth()->id())->get();
        $debtors = Debtor::where('user_id', auth()->id())->get();
        return view('accounts.add_account', compact('debtors', 'bank_accounts'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $account = new Account();
        $account->user_id = auth()->id();
        $account->debtor_id = $request->debtor;
        $account->bank_account_id = $request->bank_account;
        $account->note = $request->note;
        $account->link_pay = $request->link_pay;
        $account->save();


        $account_item = new AccountItem();
        $account_item->account_id = $account->id;
        $account_item->description = $request->description;
        $account_item->amount = $request->amount;
        $account_item->save();


        return redirect('/accounts')->with([
            'flash_message' => 'Cuenta/Factura creada!',
            'flash_message_important' => true,
            'flash_alert_type' => "success",
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Account  $account
     * @return \Illuminate\Http\Response
     */
    public function show(Account $account)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Account  $account
     * @return \Illuminate\Http\Response
     */
    public function edit(Account $account)
    {

        $bank_accounts = BankAccount::where('user_id', auth()->id())->get();
        $debtors = Debtor::where('user_id', auth()->id())->get();
        $item = AccountItem::where('account_id', $account->id)->first();
        return view('accounts.edit_account', compact('account', 'item', 'debtors', 'bank_accounts'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Account  $account
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Account $account)
    {
     
        Account::where('id', $account->id)
            ->update([
                'debtor_id' => $request->debtor,
                'bank_account_id' => $request->bank_account,
                'note' => $request->note,
                'link_pay' => $request->link_pay
            ]);

            AccountItem::where('account_id', $account->id)
            ->update([
                'description' => $request->description,
                'amount' => $request->amount,
            ]);

    
        return back()->with([
            'flash_message' => 'Cuenta/Factura Actualizada!',
            'flash_message_important' => true,
            'flash_alert_type' => "success",
        ]);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Account  $account
     * @return \Illuminate\Http\Response
     */
    public function destroy(Account $account)
    {
        //
    }

    public function print(Account $account)
    {

        $data = [
            "account" => $account,
            "bank_account" => $account->bankAccount
        ];

        $pdf = \PDF::loadView('accounts.print.receivable', compact('data'));
        return $pdf->stream('Receivable.pdf');
    }

    public function send(Account $account, ScheduledEmailService $email_handler)
    {
        $data = [
            "account" => $account,
            "bank_account" => $account->bankAccount
        ];

        $pdf = \PDF::loadView('accounts.print.receivable', compact('data'));

        $email_handler->sendEmailReceivable($account, $pdf->output());
        return redirect()->back();
    }
}

resources/views/accounts/add_account.blade.php
@extends('layouts.app')
@push('styles')
    <link rel="stylesheet" href="{{ asset('css/accounts.css') }}">
@endpush

@section('content')
    <section>

        <div class="row">
            <div class="col-12">
                <div class="card shadow-sm">
                    <form method="POST" action="{{ route('accounts.add') }}" id="add-account" name="add-account">
                        @csrf
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="debtor">Cliente</label>
                                <select class="form-control form-select" name="debtor" id="debtor" aria-label="" required>
                                    @foreach ($debtors as $debtor)
                                        <option value="{{ $debtor->id }}">{{ $debtor->business_name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="debtor">Cuenta Bancaria</label>
                                <select class="form-control form-select" name="bank_account" id="bank_account" aria-label="" required>
                                    @foreach ($bank_accounts as $bank_account)
                                        <option value="{{ $bank_account->id }}">{{ $bank_account->bank }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="note">Note</label>
                                <textarea class="form-control" id="note" name="note" rows="5" required></textarea>
                            </div>

                            <div class="form-group">
                                <label for="description">Descripción</label>
                                <textarea class="form-control" id="description" name="description" rows="5" required></textarea>
                            </div>

                            <div class="form-group">
                                <label for="note">Costo</label>
                                <input class="form-control" type="number" id="amount" name="amount" required>
                            </div>

                            <div class="form-group">
                                <label for="note">Link del Pago</label>
                                <input class="form-control" type="url" id="link_pay" name="link_pay" required>
                            </div>

                        </div>
                        <button type="submit" class="btn btn-success">Save Account</button>

                    </form>
                </div>
            </div>
        </div>
    </section>

@endsection
@section('scripts')
    <script src="{{ asset('js/accounts.js') }}"></script>
@stop

resources/views/accounts/edit_account.blade.php
@extends('layouts.app')
@push('styles')
    <link rel="stylesheet" href="{{ asset('css/accounts.css') }}">
@endpush

@section('content')
    <section>

        <div class="row">
            <div class="col-12">
                <div class="card shadow-sm">
                    <form method="POST" action="{{ route('accounts.edit', [$account]) }}" id="edit-account" name="edit-account">
                        @csrf
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="debtor">Cliente</label>
                                <select class="form-control form-select" name="debtor" id="debtor" aria-label=""
                                    required>
                                    @foreach ($debtors as $debtor)
                                        <option value="{{ $debtor->id }}"
                                            {{ $account->debtor_id == $debtor->id ? 'selected="selected"' : '' }}>
                                            {{ $debtor->business_name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="debtor">Cuenta Bancaria</label>
                                <select class="form-control form-select" name="bank_account" id="bank_account"
                                    aria-label="" required>
                                    @foreach ($bank_accounts as $bank_account)
                                        <option value="{{ $bank_account->id }}"
                                            {{ $account->bank_account_id == $bank_account->id ? 'selected="selected"' : '' }}>
                                            {{ $bank_account->bank }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="note">Note</label>
                                <textarea class="form-control" id="note" name="note" rows="5" required>{{ $account->note }}</textarea>
                            </div>

                            <div class="form-group">
                                <label for="description">Descripción</label>
                                <textarea class="form-control" id="description" name="description" rows="5" required>{{ $item->description }}</textarea>
                            </div>

                            <div class="form-group">
                                <label for="note">Costo</label>
                                <input class="form-control" type="number" id="amount" name="amount"
                                    value="{{ $item->amount }}" required>
                            </div>

                            <div class="form-group">
                                <label for="note">Link del Pago</label>
                                <input class="form-control" type="url" id="link_pay" name="link_pay" value="{{ $account->link_pay }}" required>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-success">Actualizar Cuenta/Factura</button>

                    </form>
                </div>
            </div>
        </div>
    </section>

@endsection
@section('scripts')
    <script src="{{ asset('js/accounts.js') }}"></script>
@stop

resources/views/accounts/index.blade.php
@extends('layouts.app')
@push('styles')
    <link rel="stylesheet" href="{{ asset('css/accounts.css') }}">
@endpush

@section('content')
<div class="container">
    <section>
        <div class="row align-self-end">
            <div class="col-12 col-sm-12 col-md-12 col-lg-2">
                <a class="btn btn-success btn-block text-center" href="{{ route('accounts.add') }}">
                    <i class="fas fa-plus-circle"></i> Crear Nueva Cuenta
                </a>
            </div>
        </div>
    </section>
    <section>

        <div class="row">
            <div class="col-12">
                <table id="table" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Fecha</th>
                            <th scope="col">Banco</th>
                            <th scope="col">Nota</th>
                            <th scope="col">Total</th>
                            <th class="text-center" scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($accounts as $account)
                            <tr>
                                <td>{{ $account->id }}</td>
                                <td>{{ $account->date_format_long_letter }}</td>
                                <td><a href="{{$account->bankAccount->url}}" target="_blank">{{$account->bankAccount->bank}}</a></td>
                                <td>{{ $account->note }}</td>
                                <td>{{ $account->total_account_amount }}</td>
                                <td class="text-center">
                                    <a title="Editar" class="icon icon-edit" href="{{ route('accounts.edit',[$account->id]) }}">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a title="Enviar por Email" class="icon icon-send"
                                        href="{{ route('accounts.send', ['account' => $account->id]) }}"><i
                                            class="fas fa-paper-plane"></i></a>

                                    <a title="Ver PDF" class="icon icon-see-pdf"
                                        href="{{ route('accounts.print', ['account' => $account->id]) }}"
                                        target="blank"><i class="fas fa-file-pdf"></i></a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</div>


@endsection
@section('scripts')
    <script src="{{ asset('js/accounts.js') }}"></script>
@stop