routes/web.php
<?php


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DebtorController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\BankAccountController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});




Route::get('/offline', function () {
    return view('vendor.laravelpwa.offline');
});

Auth::routes();
Route::prefix("/accounts")->group(function () {
    Route::get('/', [AccountController::class, 'index'])->name('accounts.index');
    Route::get('/add', [AccountController::class, 'create'])->name('accounts.add');
    Route::post('/add', [AccountController::class, 'store'])->name('accounts.add');
    Route::get('/edit/{account}', [AccountController::class, 'edit'])->name('accounts.edit');
    Route::post('/edit/{account}', [AccountController::class, 'update'])->name('accounts.edit');
    Route::get('/accounts/print/account/{account}', [AccountController::class, 'print'])->name('accounts.print');
    Route::get('/accounts/send/account/{account}', [AccountController::class, 'send'])->name('accounts.send');
});

Route::prefix("/debtors")->group(function () {
    Route::get('/', [DebtorController::class, 'index'])->name('debtors.index');
    Route::post('add', [DebtorController::class, 'store'])->name('debtors.add-debtor');
    Route::post('edit', [DebtorController::class, 'update'])->name('debtors.edit-debtor');
});

Route::prefix("/bank_accounts")->group(function () {
    Route::get('/', [BankAccountController::class, 'index'])->name('bank_accounts.index');
    Route::post('add', [BankAccountController::class, 'store'])->name('bank_accounts.add');
    Route::post('edit', [BankAccountController::class, 'update'])->name('bank_accounts.edit');
});


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/logout',  [App\Http\Controllers\Auth\LoginController::class, 'logout']);

app/Models/Account.php
<?php

namespace App\Models;

use NumberFormatter;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Account extends Model
{
    use HasFactory;
    protected $table = 'accounts';
    protected $fillable = [
        'user_id',
        'account_id',
        'bank_account_id',
        'note',
        'amount',
        'link_pay'
    ];

    public function user(){
        return $this->belongsTo('App\Models\User');
	}

    public function debtor(){
        return $this->belongsTo('App\Models\Debtor');
	}

    public function bankAccount(){
        return $this->belongsTo('App\Models\BankAccount');
	}

    public function items(){
        return $this->hasMany('App\Models\AccountItem','account_id');
    }

    public function getTotalAccountAmountInLettersAttribute(){
        $amount = new NumberFormatter("es", NumberFormatter::SPELLOUT);
        $totals = $this->items()->sum('amount');
        $type_currency = $totals > 999999 ? ' de pesos' : ' pesos';
        return ucfirst($amount->format($totals) .$type_currency);
    }

    public function getTotalAccountAmountAttribute(){
        return $this->items()->sum('amount');
    }

    public function getDateFormatLongLetterAttribute(){
        return date('M j, Y', strtotime($this->created_at)) ;
    }
}

app/Http/Controllers/AccountController.php
<?php

namespace App\Http\Controllers;

use App\Models\Debtor;
use App\Models\Account;
use Barryvdh\DomPDF\PDF;
use Illuminate\Http\Request;
use App\Http\Services\ScheduledEmailService;
use App\Models\AccountItem;
use App\Models\BankAccount;

class AccountController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $accounts = Account::where('user_id', auth()->id())->get();
        return view('accounts.index', compact('accounts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $bank_accounts = BankAccount::where('user_id', auth()->id())->get();
        $debtors = Debtor::where('user_id', auth()->id())->get();
        return view('accounts.add_account', compact('debtors', 'bank_accounts'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $account = new Account();
        $account->user_id = auth()->id();
        $account->debtor_id = $request->debtor;
        $account->bank_account_id = $request->bank_account;
        $account->note = $request->note;
        $account->link_pay = $request->link_pay;
        $account->save();


        $account_item = new AccountItem();
        $account_item->account_id = $account->id;
        $account_item->description = $request->description;
        $account_item->amount = $request->amount;
        $account_item->save();


        return redirect('/accounts')->with([
            'flash_message' => 'Cuenta/Factura creada!',
            'flash_message_important' => true,
            'flash_alert_type' => "success",
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Account  $account
     * @return \Illuminate\Http\Response
     */
    public function show(Account $account)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Account  $account
     * @return \Illuminate\Http\Response
     */
    public function edit(Account $account)
    {

        $bank_accounts = BankAccount::where('user_id', auth()->id())->get();
        $debtors = Debtor::where('user_id', auth()->id())->get();
        $item = AccountItem::where('account_id', $account->id)->first();
        return view('accounts.edit_account', compact('account', 'item', 'debtors', 'bank_accounts'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Account  $account
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Account $account)
    {
     
        Account::where('id', $account->id)
            ->update([
                'debtor_id' => $request->debtor,
                'bank_account_id' => $request->bank_account,
                'note' => $request->note,
                'link_pay' => $request->link_pay
            ]);

            AccountItem::where('account_id', $account->id)
            ->update([
                'description' => $request->description,
                'amount' => $request->amount,
            ]);

    
        return back()->with([
            'flash_message' => 'Cuenta/Factura Actualizada!',
            'flash_message_important' => true,
            'flash_alert_type' => "success",
        ]);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Account  $account
     * @return \Illuminate\Http\Response
     */
    public function destroy(Account $account)
    {
        //
    }

    public function print(Account $account)
    {

        $data = [
            "account" => $account,
            "bank_account" => $account->bankAccount
        ];

        $pdf = \PDF::loadView('accounts.print.receivable', compact('data'));
        return $pdf->stream('Receivable.pdf');
    }

    public function send(Account $account, ScheduledEmailService $email_handler)
    {
        $data = [
            "account" => $account,
            "bank_account" => $account->bankAccount
        ];

        $pdf = \PDF::loadView('accounts.print.receivable', compact('data'));

        $email_handler->sendEmailReceivable($account, $pdf->output());
        return redirect()->back();
    }
}

resources/views/accounts/print/receivable.blade.php
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Receivable</title>
    <style>
        html {
            min-height: 100%;
            position: relative;
            font-size: 62.5%;
            font-family: "DM Sans", sans-serif;
        }

        body {
            margin: 0;
            margin-bottom: 40px;
        }

        .text-center {
            text-align: center;
        }

        .information-debtor {
            margin-bottom: 100px;
        }

        .user-information,
        .account-information {
            margin-bottom: 80px;
        }

        .debtor-name {
            font-size: 1.5rem;
            line-height: 0.1rem;
            font-weight: bold;
        }

        .title-footer {
            text-align: center;
            font-size: 8px;
        }

        .title-footer a {
            text-decoration: none;
        }

        .receivable-title {
            font-size: 1.3rem;
            line-height: 0.1rem;
            font-weight: bold;
        }

        .receivable-data {
            font-size: 1.3rem;
            line-height: 0.1rem;
            font-weight: normal;
        }

        table,
        th,
        td {
            border: 1px solid black;
            border-collapse: collapse;
        }

        .pago {
            margin: 0px 10% 0px 10%;
        }

        .title-table {
            text-align: center;
            font-weight: bold;
        }

        .footer-pdf {
            position: absolute;
            bottom: 40px;
            width: 100%;
            height: 120px;
        }


        #img-firm {
            margin: 0px;
            padding: 0px;
            width: 150px;
            height: 45px;
        }

        #line-firm {
            margin: 0px;
            padding: 0px;
        }

        .footer-pdf h6 {
            margin: 0px;
            padding-top: 15px;
        }
    </style>

</head>

<body>
    <section class="text-center header mt-3">
        <h1>CUENTA DE COBRO</h1>
    </section>
    <section class="text-center content-pdf">
        <section class="information-debtor">
            <h6 class="debtor-name">{{ $data['account']->debtor->business_name }}</h6>
            <h6 class="receivable-data">NIT: {{ $data['account']->debtor->nit }}</h6>
        </section>

        <section class="user-information">
            <h6 class="receivable-title">DEBE A:</h6>
            <h6 class="receivable-data">{{ $data['account']->user->name }}</h6>
            <h6 class="receivable-data">C.C. {{ $data['account']->user->nit }}</h6>
        </section>


        <section class="account-information">
            <h6 class="receivable-title">LA SUMA DE:</h6>
            <h6 class="receivable-data">${{ $data['account']->total_account_amount }}
                ({{ $data['account']->total_account_amount_in_letters }})</h6>
        </section>


        <section class="items-information">
            <h6 class="receivable-title">POR CONCEPTO DE:</h6>
            @foreach ($data['account']->items as $item)
                <h6 class="receivable-data">{{ $item->description }}</h6>
            @endforeach
        </section>

        <section class="items-information">
            <h6 class="receivable-title">DONDE PAGAR</h6>

            <table class="pago" width="80%">
                <thead>
                    <tr>

                        <td class="title-table">Número de cuenta bancaria</td>

                        <td class="title-table">Link de pago</td>

                        <td class="title-table">Qr de pago</td>

                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ $data['bank_account']->number . ' (Tipo de cuenta: ' . $data['bank_account']->account_type . ' ' . $data['bank_account']->bank . ' )' }}
                        </td>
                        <td>{{ $data['account']->link_pay }}</td>
                        <td>NA</td>
                    </tr>
                </tbody>
            </table>
        </section>
    </section>

    <section class="footer-pdf">
        <h6 class="receivable-title">Cordialmente,</h6>
        <br><br><br>

        <div class="firm">
            <img id="img-firm" src="https://s3.us-east-2.amazonaws.com/public.personal/Firma.jpeg" alt="firm">
            <h6 id="line-firm">__________________________________________________</h6>
        </div>
        <h6 class="receivable-data">{{ $data['account']->user->name }}</h6>
        <h6 class="receivable-data">C.C. {{ $data['account']->user->nit }}</h6>
        <h6 class="receivable-data">Valledupar, {{ Date('d') . ' de ' . Date('M') . ' del ' . Date('Y') }}</h6>
        <br><br>
        <hr>
        <div class="text-center">
            <span class="title-footer">Este es un producto de <a href="http://qesoft.com.co/">QE SOFT</a></span>
        </div>
    </section>


</body>

</html>